# Generated by Django 2.0.4 on 2018-04-16 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=10)),
                ('pincode', models.IntegerField()),
                ('street_address', models.CharField(max_length=300)),
                ('landmark', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.UserType'),
        ),
    ]
