# Generated by Django 2.0.4 on 2018-04-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180417_0630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
