# Generated by Django 2.0.4 on 2018-04-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
